[package]
name = "futures-example"
version = "0.1.0"
edition = "2021"
publish = false
description = "Generic futures example for ranked-semaphore"

[[bin]]
name = "basic"
path = "src/main.rs"

[dependencies]
ranked-semaphore = { workspace = true }
futures = { workspace = true }
